feat: Add user verify code sign  type feature
openbuildxyz/openbuild-frontend pull request #17
Opened 2024-12-20 15:03 UTC by UstinianMobius

- New email authentication code login method
- Removed yarn.lock, added npm-lock.yaml
- The SvgIcon component receives the Change event
- Resolves #7

2024-12-21 06:59 UTC, ourai requested changes
The functionality part will be reviewed when the Vercel preview environment is ready.

2024-12-21 06:59 UTC, ourai commented on package.json
> +  "packageManager": "pnpm@9.15.1+sha512.1acb565e6193efbebda772702950469150cf12bcc764262e7587e71d19dc98a423dff9536e57ea44c49bdf790ff694e83c27be5faa23d67e0c033b583be4bfcf"
This field doesn't need to be specified for now.

2024-12-21 06:59 UTC, ourai commented on src/app/(uc)/signin/page.js
> +"use client";
We use single quote for strings.

2024-12-21 06:59 UTC, ourai commented on yarn.lock
The `yarn.lock` file couldn't be deleted, or Vercel build errors will occur.

2024-12-22 16:25 UTC, UstinianMobius commented on yarn.lock
The problem has been solved. 
1: The yarn.lock file is retained.If you switch to pnpm later, should change the vercel configuration again. 
2: Format the file with single quotes

2024-12-29 11:53 UTC, closed without merging