feat: SVG组件优化
openbuildxyz/openbuild-frontend pull request #18
Opened 2024-12-21 00:53 UTC by missop

2024-12-21 05:30 UTC, ourai commented on src/app/home/Main.js
> +           <Spin/>
自闭合标签斜杠前应留个空格出来

2024-12-21 05:33 UTC, ourai requested changes

2024-12-21 05:33 UTC, ourai commented on src/app/home/Main.js
> +function Spin() {
这段移到单独的文件里，放在跟当前文件同一个文件夹下。

2024-12-21 05:33 UTC, ourai commented on src/app/home/Main.js
> +           <Spin/>
自闭合标签斜杠前应留个空格出来

2024-12-23 11:55 UTC, missop commented on src/app/home/Main.js
> +           <Spin/>
已经改好了

2024-12-23 12:11 UTC, ourai approved these changes

2024-12-23 12:11 UTC, merged