chore: add quick start
openbuildxyz/openbuild-frontend pull request #29
Opened 2024-12-26 15:07 UTC by smallfu6

1. 在 README 中添加 quick start 部分

2024-12-27 12:43 UTC, ourai requested changes

2024-12-30 07:09 UTC, smallfu6 commented on README.md
> +- [pnpm](https://pnpm.io/)
因为后面的命令需要用到，小白直接叫他这么操作（不用选择）； 熟悉的人肯定知道这个不是强制

2024-12-30 07:09 UTC, smallfu6 commented on README.md
> +- [pnpm](https://pnpm.io/)
因为后面的命令需要用到，小白直接叫他这么操作（不用选择）； 熟悉的人肯定知道这个不是强制

2024-12-30 07:23 UTC, ourai approved these changes

2024-12-30 07:23 UTC, merged